#!/usr/bin/env python3
"""Export the PFO Tax Strategy Calculator workbook into JavaScript data modules.

Produces two files:
  src/excel/workbook-data.js       formulas + constants + yellow input cells (the "Excel replica" model)
  tests/fixtures/workbook-cached.js  the values Excel last calculated, used to prove the replica matches

Usage (from the tax-calculator folder):
  python3 tools/export_workbook.py "path/to/Tax Strategy Calculator.xlsx"

Requires openpyxl (pip install openpyxl). Re-run whenever the workbook changes, then run the tests.
Client names are not exported; the sheets only contain numbers, labels and formulas.
"""
import argparse
import datetime
import json
import os
import re
import sys

try:
    import openpyxl
except ImportError:  # pragma: no cover
    sys.exit("openpyxl is required: pip install openpyxl")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_EXCLUDE = [r"^RGP Income Fund"]
YELLOW = {"FFFFFF00", "00FFFF00"}


def is_yellow(cell):
    f = cell.fill
    if not f or f.fill_type != "solid":
        return False
    c = f.fgColor
    return c is not None and c.type == "rgb" and str(c.rgb).upper() in YELLOW


def js_value(v):
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        return v
    if v is None:
        return None
    if isinstance(v, (datetime.date, datetime.datetime)):
        return v.isoformat()
    return str(v)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("xlsx")
    ap.add_argument("--exclude", action="append", default=None,
                    help="regex of sheet names to skip (default: RGP Income Fund sheets)")
    args = ap.parse_args()
    exclude = [re.compile(p) for p in (args.exclude or DEFAULT_EXCLUDE)]

    wb_f = openpyxl.load_workbook(args.xlsx)                  # formulas
    wb_v = openpyxl.load_workbook(args.xlsx, data_only=True)  # Excel's cached results

    sheets, inputs, cached, init = {}, {}, {}, {}
    order = []
    for ws in wb_f.worksheets:
        if any(p.search(ws.title) for p in exclude):
            continue
        order.append(ws.title)
        cells, yellow = {}, []
        wv = wb_v[ws.title]
        for row in ws.iter_rows():
            for c in row:
                if is_yellow(c):
                    yellow.append(c.coordinate)
                if c.value is None:
                    continue
                v = c.value
                if isinstance(v, str) and v.startswith("="):
                    formula = v.replace("\r", " ").replace("\n", " ")
                    cells[c.coordinate] = formula
                    cv = wv[c.coordinate].value
                    key = f"{ws.title}!{c.coordinate}"
                    if isinstance(cv, str) and cv.startswith("#"):
                        cached[key] = {"error": cv}
                    else:
                        cached[key] = js_value(cv)
                    # Self-referencing (iterative) cells need Excel's last value as a starting point.
                    if re.search(r"(?<![A-Z$!])\$?" + re.sub(r"(\D+)(\d+)", r"\1\\$?\2", c.coordinate) + r"(?!\d)", formula[1:]):
                        init[key] = js_value(cv)
                else:
                    cells[c.coordinate] = js_value(v)
        sheets[ws.title] = cells
        if yellow:
            inputs[ws.title] = yellow

    calc = wb_f.calculation
    meta = {
        "source": "PFO Tax Strategy Calculator workbook (10.1.26 template)",
        "exported": datetime.date.today().isoformat(),
        "iterativeCalc": bool(calc.iterate),
        "iterateCount": calc.iterateCount or 100,
        "iterateDelta": calc.iterateDelta or 0.001,
        "excludedSheets": [ws.title for ws in wb_f.worksheets if ws.title not in order],
    }

    model = {"meta": meta, "order": order, "inputs": inputs, "init": init, "sheets": sheets}
    out_model = os.path.join(ROOT, "src", "excel", "workbook-data.js")
    out_cached = os.path.join(ROOT, "tests", "fixtures", "workbook-cached.js")
    header = "// GENERATED by tools/export_workbook.py. Do not edit by hand; re-export from the workbook.\n"
    with open(out_model, "w") as fh:
        fh.write(header + "export default " + json.dumps(model, separators=(",", ":")) + ";\n")
    with open(out_cached, "w") as fh:
        fh.write(header + "export default " + json.dumps(cached, separators=(",", ":")) + ";\n")
    n_formulas = sum(1 for s in sheets.values() for v in s.values() if isinstance(v, str) and v.startswith("="))
    print(f"sheets={len(order)} formulas={n_formulas} inputs={sum(map(len, inputs.values()))} "
          f"iterative={sorted(init)}")
    print(f"wrote {os.path.relpath(out_model)} ({os.path.getsize(out_model)//1024} KB), "
          f"{os.path.relpath(out_cached)} ({os.path.getsize(out_cached)//1024} KB)")


if __name__ == "__main__":
    main()
